### ISSUE TITLE
CloudFlare and HINFO	"ANY obsoleted" "See draft-ietf-dnsop-refuse-any"

### ISSUE THREAD

**Issue by lota** [icann-dns/zonecheck#2]
Hi team,
I discovered that when you perform a test (without options) on domains using CloudFlare DNS appers this Error:

f> SOA and ANY request disagree

this seems to happen because CloudFlare choose not give result for record ANY

i.e.
$ dig +short @ram.ns.cloudflare.com ANY  escalibur.eu
"ANY obsoleted" "See draft-ietf-dnsop-refuse-any"

As you can see on the CloudFlare Blog [1] they Deprecating the DNS ANY meta-query type.

Consider to remove this test on default check.

HTH
Alessandro Lota

[1] https://blog.cloudflare.com/deprecating-dns-any-meta-query-type/

**Comment by b4ldr** [comment]
@lota can you please provide an example of how you are preforming the tests.  i have just checked the source code and i dont think any 'ANY' requests are preformed.

**Comment by lota** [comment]
sorry for delay,

$ dig +short ANY @desi.ns.cloudflare.com escalibur.eu
"ANY obsoleted" "See draft-ietf-dnsop-refuse-any"

$ zonecheck -4 escalibur.eu
ZONE  : escalibur.eu
NS <= : desi.ns.cloudflare.com [173.245.58.96, 2400:CB00:2049:1::ADF5:3A60]
NS    : ram.ns.cloudflare.com [173.245.59.225, 2400:CB00:2049:1::ADF5:3BE1]

       _______________
     ,---------------.|
~~~~ |    warning    || ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     `---------------'
w> The format of the serial number is not YYYYMMDDnn
 | Ref: RFC1912 (p.3)
 |   The recommended syntax is YYYYMMDDnn (YYYY=year, MM=month, DD=day,
 | nn=revision number).
 `----- -- -- - -  -
 :   The serial 2028125972 doesn't seem to be in the YYYYMMDDnn format.
 `..... .. .. . .  .
=> ram.ns.cloudflare.com/173.245.59.225
=> desi.ns.cloudflare.com/173.245.58.96

       _____________
     ,-------------.|
~~~~ |    fatal    || ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     `-------------'
f> SOA and ANY request disagree
=> ram.ns.cloudflare.com/173.245.59.225

==> FAILURE (and 2 warning(s))

**Comment by b4ldr** [comment]
@lota i believe you are using the AFNIC zonecheck tool[1] as far as i know development for this tool has ceased however you may be interested zonemaster[2][3] which is the tool created to replace zonecheck.  Sorry for the confusion i should have named this project something elses

[1]https://linux.die.net/man/1/zonecheck 
[2]https://www.zonemaster.net/
[3]https://github.com/zonemaster/zonemaster

**Comment by lota** [comment]
@b4ldr you right! sorry for misandesting, on my Debian system only zonecheck is available ;-)
